### ISSUE TITLE
can you add \r?\n to the pegasus.grammar file and regenerate the grammar_parser for windows?

### ISSUE THREAD

**Issue by dsisnero** [DanilaFe/pegasus#8]
Not able to use in windows - each grammar is breaking because of windows newline

**Comment by DanilaFe** [comment]
Woah, Crystal on Windows! That wasn't a thing around when I was working on Pegasus actively (as you can probably tell). Let me see what I can do.

**Comment by DanilaFe** [comment]
Should be working on master, let me know if you run into any other problems :)

**Comment by dsisnero** [comment]
Still getting an error.  Not sure why
------

```
f:\programming\source\repos\git\dsisnero\crystal_examples\pegasus>git pull
Already up to date.
```

```
f:\programming\source\repos\git\dsisnero\crystal_examples\pegasus>shards build --release
Dependencies are satisfied
Building: pegasus
Building: pegasus-dot
Building: pegasus-sim
Building: pegasus-c
Building: pegasus-csem
Building: pegasus-crystal
Building: pegasus-crystalsem
```

`f:\programming\source\repos\git\dsisnero\crystal_examples\pegasus>echo 'token hello = "Hello world!"; rule S = hello;' > test.grammar`

```
f:\programming\source\repos\git\dsisnero\crystal_examples\pegasus>.\bin\pegasus.exe < test.grammar
an error has occured while parsing the grammar definition: Invalid character 39 at position 0
```

`f:\programming\source\repos\git\dsisnero\crystal_examples\pegasus>   `

**Comment by dsisnero** [comment]
Never mind.  It works now.  Updated README.md to fix example for token
